pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "frontend:latest"
        CONTAINER_NAME = "frontend-container"
        DOCKER_REGISTRY = "docker.io/tharushikas/frontend"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/TharushikaS/book-store-mern-project_.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build Frontend') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
                sh 'docker tag $DOCKER_IMAGE $DOCKER_REGISTRY:latest'
                sh 'docker push $DOCKER_REGISTRY:latest'
            }
        }

        stage('Deploy to Server') {
            steps {
                sh 'docker stop $CONTAINER_NAME || true'
                sh 'docker rm $CONTAINER_NAME || true'
                sh 'docker run -d -p 8081:80 --name $CONTAINER_NAME $DOCKER_REGISTRY:latest'
            }
        }
    }
}
