name: Deploy Frontend

on:
  push:
    branches:
      - main  # Change to your main branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Build Docker Image
        run: docker build -t username/my-frontend:latest .

      - name: Push Docker Image
        run: docker push username/my-frontend:latest
